<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\bin\Release</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Include="paket.references" />
    <Compile Include="CooTransformation.fs" />
    <Compile Include="DefaultSpiceKernels.fs" />
    <Compile Include="CooTransformation.FSharp.fs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="resources\defaultSpiceKernel\pck00010.tpc" />
    <EmbeddedResource Include="resources\defaultSpiceKernel\pck00010-base.tpc" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>