name: Test 
on:
  push:
    branches:
      - main
jobs:
  mac_x64:
    name: OSX (x64)
    runs-on: macos-13
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}
      - name: Restore tools
        run: bash dotnet tool restore
      - name: Restore paket
        run: bash dotnet paket restore
      - name: Build
        run: bash dotnet run --project src/PRo3D.SPICE.Tests/PRo3D.SPICE.Tests.fsproj
