name: Test 
on:
  push:
    branches:
      - main
jobs:
  mac_x64:
    name: OSX (x64)
    runs-on: macos-13
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: true
      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore paket
        run: dotnet paket restore
      - name: Build
        run: dotnet run --project src/PRo3D.SPICE.Tests/PRo3D.SPICE.Tests.fsproj
