name: Test 
on:
  push:
    branches:
      - main
jobs:
  mac_x64:
    name: OSX (x64)
    runs-on: macos-13
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore paket
        run: dotnet paket restore
      - name: Build
        run: dotnet run --project src/PRo3D.SPICE.Tests/PRo3D.SPICE.Tests.fsproj
